require:
  - standard
  - rubocop-rails

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/*'
  NewCops: enable

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: single_quotes
